### PR TITLE
Allows multiple send in one call

### PR DESCRIPTION
**Pull request by JbIPS**
When sending to multiple recipients, SendGrid let you choose between a mass email or one email per address.

:warning: dependent of #8

### CODE REVIEW

**Comment by zuhito** [comment]
Hmm... the checkbox for multiple is needed? I think that the code handles multiple recipients besed on To format (Array, one e-mail address, multiple e-mail address separated by semi-colon, space or comma) without the checkbox automatically.

**Comment by JbIPS** [comment]
I should add more information on that but what 'multiple' changes is to send one mail per recipient instead of one mail for all.

**Comment by zuhito** [comment]
I understand the use case of the checkbox but I think that multiple sending can be realized without the checkbox. When the input message is an array, the node automatically sends the e-mail to multiple recipients.

**Comment by JbIPS** [comment]
Yes, the difference is one email to n recipients or n email to one recipient. When I send newsletters I don't want everybody to see the addresses of all the recipients

**Comment by zuhito** [comment]
Thank you for describing your situation. After I considered it deeply, the checkbox will be useful to avoid the miss settings of the recipients in my opinion (There may be some risk to know recipient addresses when automatic multiple/single mail handling due to incorrect input of flow).
And I published the node as v0.2.1 after making the property UI simpler for beginner users!
https://flows.nodered.org/node/node-red-contrib-sendgrid
I appreciate it if you check the node. Thank you for your contributions!

**Comment by JbIPS** [comment]
Nice update, love the UI!

**Comment by zuhito** [comment]
Thank you for your checking it!

**Pull request merged**
